new approach

diff --git a/.github/workflows/checkIds.yml b/.github/workflows/checkIds.yml
--- a/.github/workflows/checkIds.yml
+++ b/.github/workflows/checkIds.yml
@@ -7,20 +7,49 @@ on:
 
 jobs:
   check-merge-ids:
-    uses: jgmeet/jira-integration/.github/workflows/merge-check.yml@main
-    with:
-      EMAIL: ${{ secrets.EMAIL }}
-      API_TOKEN: ${{ secrets.API_TOKEN }}
+    runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout template repository
+    - name: Checkout repository content
       uses: actions/checkout@v4
-      with:
-        repository: jgmeet/jira-integration
-        path: templates
 
-    - name: Run Template Workflow
+    - name: Extract CM and Jira Issue IDs from PR description
+      id: extract_issue_ids
       run: |
-        cp -r templates/. .
-        npm install
-        node checkMergeDescriptionIDs.js
+        CM_REGEX='#CM-[0-9]+'
+        JIRA_REGEX='#([A-Z]+[A-Z0-9]*-[0-9]+)'
+
+        # Get the pull request description
+        PR_DESCRIPTION="${{ github.event.pull_request.body }}"
+
+        # Extract all matching JIRA IDs
+        CM_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)
+        OTHER_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$JIRA_REGEX" | grep -vE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)
+
+        if [ -z "$CM_IDS" ]; then
+          echo "ERROR: No change-management issue id found in PR description."
+          exit 1
+        fi
+
+        if [ -z "$OTHER_IDS" ]; then
+          echo "ERROR: No JIRA project issue found in PR description."
+          exit 1
+        fi
+
+        # Extract repo name
+        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
+
+        echo "Change-management IDs: $CM_IDS"
+        echo "Other JIRA issue IDs: $OTHER_IDS"
+        echo "Repo Name: $REPO_NAME"
+        echo "cm_ids=$CM_IDS" >> $GITHUB_ENV
+        echo "jira_ids=$OTHER_IDS" >> $GITHUB_ENV
+        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
+
+
+    - name: Use reusable workflow
+      uses: jgmeet/jira-integration/.github/workflows/merge-check.yml@main
+      with:
+        CM_IDS: ${{ env.cm_ids }}
+        JIRA_IDS: ${{ env.jira_ids }}
+        REPO_NAME: ${{ env.repo_name }}
